# frozen_string_literal: true

source "https://rubygems.org"

if ENV["RAILS_VERSION"] == "edge"
  gem "rails", github: "rails/rails"
else
  gem "rails", "~> #{ENV["RAILS_VERSION"] || "7.0.0"}"
end

# Use SCSS for stylesheets
gem "sass-rails", ">= 6"

gem "unicorn"
gem "pg", "~> 1.3.0"
gem "byebug"
gem "rails_failover", path: "../../.."
gem "psych", "~> 3.0"
gem "listen"
