production:
  adapter: postgresql
  pool: 15
  timeout: 5000
  database: dummy_app_production
  host: "/home/tgxworld/work/rails_failover/tmp/primary/run"
  port: 5434
  replica_host: "/home/tgxworld/work/rails_failover/tmp/replica/run"
  replica_port: 5435
