production:
  primary:
    adapter: postgresql
    pool: 15
    timeout: 5000
    database: test
    host: localhost
    port: 5434
    replica_host: localhost
    replica_port: 5435
  two:
    adapter: postgresql
    pool: 10
    timeout: 5000
    database: test
    host: localhost
    port: 5434
    replica_host: localhost
    replica_port: 5435
