name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop

  redis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup redis
        run: sudo apt-get install redis-server

      - name: Redis specs
        run: bin/rspec redis

  activerecord:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        rails: ['6.1.0']
        include:
          - ruby: '3.2'
            rails: '6.0.0'

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup gems
        run: bundle install

      - name: Setup postgres
        run: |
          make setup_pg
          make start_pg

      - name: ActiveRecord specs
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: bin/rspec active_record

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, redis, activerecord]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
