name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: ${{ matrix.build_types }}

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
          - 2.7
        build_types: ["LINT", "REDIS", "ACTIVERECORD"]
        exclude:
          - ruby: 2.6
            build_types: "LINT"

    steps:
      - uses: actions/checkout@v1

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Setup bundler
        run: gem install bundler

      - name: Setup gems
        run: bundle install

      - name: Rubocop
        run: bundle exec rubocop
        if: env.BUILD_TYPE == 'LINT'

      - name: Setup redis
        run: sudo apt-get install redis-server
        if: env.BUILD_TYPE == 'REDIS'

      - name: Redis specs
        run: bin/rspec redis
        if: env.BUILD_TYPE == 'REDIS'

      - name: Setup test app gems
        run: cd spec/support/dummy_app && bundle install
        if: env.BUILD_TYPE == 'ACTIVERECORD'

      - name: Setup postgres
        run: |
          make setup_pg
          make start_pg
        if: env.BUILD_TYPE == 'ACTIVERECORD'

      - name: ActiveRecord specs
        run: bin/rspec active_record
        if: env.BUILD_TYPE == 'ACTIVERECORD'

  publish:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
