name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop

      - name: syntax_tree
        if: ${{ !cancelled() }}
        run: |
          set -E
          bundle exec stree check Gemfile rails_failover.gemspec $(git ls-files '*.rb')

  redis:
    name: "Redis (Redis gem ~> ${{ matrix.redis_gem }}, Ruby ${{ matrix.ruby }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "3.3", "3.2", "3.1"]
        redis_gem: ["4.8", "5.3"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup gems
        env:
          REDIS_GEM_VERSION: ${{ matrix.redis_gem }}
        run: bundle install

      - name: Setup redis
        run: sudo apt-get install redis-server

      - name: Redis specs
        env:
          REDIS_GEM_VERSION: ${{ matrix.redis_gem }}
        run: bin/rspec redis

  active_record:
    runs-on: ubuntu-latest
    name: "ActiveRecord ~>${{ matrix.rails }} (Ruby ${{ matrix.ruby }})"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "3.3", "3.2", "3.1"]
        rails: ["7.1.0", "7.0.0"]
        include:
          - ruby: "3.2"
            rails: "6.1.0"
        exclude:
          - ruby: "3.4"
            rails: "7.0.0"
          - ruby: "3.3"
            rails: "7.0.0"

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup gems
        run: bundle install

      - name: Setup postgres
        run: |
          make setup_pg

      - name: ActiveRecord specs
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: bin/rspec active_record

      - name: Dump Unicorn STDERR logs
        if: ${{ failure() }}
        run: cat spec/support/dummy_app/log/unicorn.stderr.log

      - name: Dump Rails logs
        if: ${{ failure() }}
        run: cat spec/support/dummy_app/log/production.log

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, redis, active_record]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v3
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
